/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Endpoints + GCF
 * Jural Backend for Cloud Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlowPatchRequestParameters
 */
export interface FlowPatchRequestParameters {
    /**
     * 
     * @type {string}
     * @memberof FlowPatchRequestParameters
     */
    name?: string;
}

/**
 * Check if a given object implements the FlowPatchRequestParameters interface.
 */
export function instanceOfFlowPatchRequestParameters(value: object): boolean {
    return true;
}

export function FlowPatchRequestParametersFromJSON(json: any): FlowPatchRequestParameters {
    return FlowPatchRequestParametersFromJSONTyped(json, false);
}

export function FlowPatchRequestParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowPatchRequestParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function FlowPatchRequestParametersToJSON(value?: FlowPatchRequestParameters | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

