/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Endpoints + GCF
 * Jural Backend for Cloud Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InputInstance
 */
export interface InputInstance {
    /**
     * 
     * @type {string}
     * @memberof InputInstance
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof InputInstance
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof InputInstance
     */
    type?: string;
}

/**
 * Check if a given object implements the InputInstance interface.
 */
export function instanceOfInputInstance(value: object): boolean {
    return true;
}

export function InputInstanceFromJSON(json: any): InputInstance {
    return InputInstanceFromJSONTyped(json, false);
}

export function InputInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function InputInstanceToJSON(value?: InputInstance | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
        'type': value['type'],
    };
}

