/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Endpoints + GCF
 * Jural Backend for Cloud Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlowCreateRequestParameters
 */
export interface FlowCreateRequestParameters {
    /**
     * 
     * @type {string}
     * @memberof FlowCreateRequestParameters
     */
    inputType?: string;
    /**
     * 
     * @type {string}
     * @memberof FlowCreateRequestParameters
     */
    outputType?: string;
}

/**
 * Check if a given object implements the FlowCreateRequestParameters interface.
 */
export function instanceOfFlowCreateRequestParameters(value: object): boolean {
    return true;
}

export function FlowCreateRequestParametersFromJSON(json: any): FlowCreateRequestParameters {
    return FlowCreateRequestParametersFromJSONTyped(json, false);
}

export function FlowCreateRequestParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowCreateRequestParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'inputType': json['inputType'] == null ? undefined : json['inputType'],
        'outputType': json['outputType'] == null ? undefined : json['outputType'],
    };
}

export function FlowCreateRequestParametersToJSON(value?: FlowCreateRequestParameters | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'inputType': value['inputType'],
        'outputType': value['outputType'],
    };
}

