/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Endpoints + GCF
 * Jural Backend for Cloud Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlowRunResponseResponse
 */
export interface FlowRunResponseResponse {
    /**
     * 
     * @type {string}
     * @memberof FlowRunResponseResponse
     */
    output?: string;
    /**
     * 
     * @type {string}
     * @memberof FlowRunResponseResponse
     */
    responseStatus?: FlowRunResponseResponseResponseStatusEnum;
}


/**
 * @export
 */
export const FlowRunResponseResponseResponseStatusEnum = {
    Success: 'success',
    UnknownError: 'unknown_error'
} as const;
export type FlowRunResponseResponseResponseStatusEnum = typeof FlowRunResponseResponseResponseStatusEnum[keyof typeof FlowRunResponseResponseResponseStatusEnum];


/**
 * Check if a given object implements the FlowRunResponseResponse interface.
 */
export function instanceOfFlowRunResponseResponse(value: object): boolean {
    return true;
}

export function FlowRunResponseResponseFromJSON(json: any): FlowRunResponseResponse {
    return FlowRunResponseResponseFromJSONTyped(json, false);
}

export function FlowRunResponseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowRunResponseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'output': json['output'] == null ? undefined : json['output'],
        'responseStatus': json['response_status'] == null ? undefined : json['response_status'],
    };
}

export function FlowRunResponseResponseToJSON(value?: FlowRunResponseResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'output': value['output'],
        'response_status': value['responseStatus'],
    };
}

