/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Endpoints + GCF
 * Jural Backend for Cloud Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FlowModificationRequestParameters } from './FlowModificationRequestParameters';
import {
    FlowModificationRequestParametersFromJSON,
    FlowModificationRequestParametersFromJSONTyped,
    FlowModificationRequestParametersToJSON,
} from './FlowModificationRequestParameters';

/**
 * 
 * @export
 * @interface FlowModificationRequest
 */
export interface FlowModificationRequest {
    /**
     * 
     * @type {FlowModificationRequestParameters}
     * @memberof FlowModificationRequest
     */
    parameters?: FlowModificationRequestParameters;
}

/**
 * Check if a given object implements the FlowModificationRequest interface.
 */
export function instanceOfFlowModificationRequest(value: object): boolean {
    return true;
}

export function FlowModificationRequestFromJSON(json: any): FlowModificationRequest {
    return FlowModificationRequestFromJSONTyped(json, false);
}

export function FlowModificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowModificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'parameters': json['parameters'] == null ? undefined : FlowModificationRequestParametersFromJSON(json['parameters']),
    };
}

export function FlowModificationRequestToJSON(value?: FlowModificationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'parameters': FlowModificationRequestParametersToJSON(value['parameters']),
    };
}

