/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Endpoints + GCF
 * Jural Backend for Cloud Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputInstance } from './InputInstance';
import {
    InputInstanceFromJSON,
    InputInstanceFromJSONTyped,
    InputInstanceToJSON,
} from './InputInstance';

/**
 * 
 * @export
 * @interface FlowRunRequestParameters
 */
export interface FlowRunRequestParameters {
    /**
     * 
     * @type {Array<InputInstance>}
     * @memberof FlowRunRequestParameters
     */
    input?: Array<InputInstance>;
}

/**
 * Check if a given object implements the FlowRunRequestParameters interface.
 */
export function instanceOfFlowRunRequestParameters(value: object): boolean {
    return true;
}

export function FlowRunRequestParametersFromJSON(json: any): FlowRunRequestParameters {
    return FlowRunRequestParametersFromJSONTyped(json, false);
}

export function FlowRunRequestParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowRunRequestParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'] == null ? undefined : ((json['input'] as Array<any>).map(InputInstanceFromJSON)),
    };
}

export function FlowRunRequestParametersToJSON(value?: FlowRunRequestParameters | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'input': value['input'] == null ? undefined : ((value['input'] as Array<any>).map(InputInstanceToJSON)),
    };
}

