/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Endpoints + GCF
 * Jural Backend for Cloud Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FlowPatchRequestParameters } from './FlowPatchRequestParameters';
import {
    FlowPatchRequestParametersFromJSON,
    FlowPatchRequestParametersFromJSONTyped,
    FlowPatchRequestParametersToJSON,
} from './FlowPatchRequestParameters';

/**
 * 
 * @export
 * @interface FlowPatchRequest
 */
export interface FlowPatchRequest {
    /**
     * 
     * @type {FlowPatchRequestParameters}
     * @memberof FlowPatchRequest
     */
    parameters?: FlowPatchRequestParameters;
}

/**
 * Check if a given object implements the FlowPatchRequest interface.
 */
export function instanceOfFlowPatchRequest(value: object): boolean {
    return true;
}

export function FlowPatchRequestFromJSON(json: any): FlowPatchRequest {
    return FlowPatchRequestFromJSONTyped(json, false);
}

export function FlowPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'parameters': json['parameters'] == null ? undefined : FlowPatchRequestParametersFromJSON(json['parameters']),
    };
}

export function FlowPatchRequestToJSON(value?: FlowPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'parameters': FlowPatchRequestParametersToJSON(value['parameters']),
    };
}

